### ISSUE TITLE
download page not found.

### ISSUE THREAD

**Issue by mmarchjr** [AlexanderDefuria/FRC-Scouting#112]
The download page is not working for downloading the raspi images.

**Comment by AlexanderDefuria** [comment]
At the moment the raspi images are deprecated. Please use the .deb install to setup swiss on your raspi. I can provide further detail as to how to setup the whole stack if you need.

**Comment by mmarchjr** [comment]
ok, that would be much appreciated
also, is there any chance that this will be semi-usable by march 14?
