### ISSUE TITLE
Missed teleop balls being counted as missed auto balls, missed auto balls not connecting to backend 

### ISSUE THREAD

**Issue by NickKerstens** [AlexanderDefuria/FRC-Scouting#39]
According to views.py, frontend missed_balls is getting posted as missed_balls_auto. frontend missed_balls_auto is getting posted as missed_auto, which doesn't appear in models.py (unless I skimmed over it by mistake)

**Comment by AlexanderDefuria** [comment]
Will correct shortly. Thanks.

**Comment by AlexanderDefuria** [comment]
Fixed
