### ISSUE TITLE
Match complete button and flag for Schedule View

### ISSUE THREAD

**Issue by NickKerstens** [AlexanderDefuria/FRC-Scouting#74]
Add functionality to mark matches as completed to prevent this scary wall of matches. 
Also add separate areas and styling for upcoming/completed matches. 

![messages_0](https://user-images.githubusercontent.com/34928894/182431526-11a3111b-8b84-413e-80e8-cabe747171ef.png)

**Comment by AlexanderDefuria** [comment]
@NickKerstens Just needs a little styling on the button to show completed matches.

The default behaviour is for all new matches that are scouted to be marked as completed when a team is scouted for that match. The completed status can be changed via admin panel.

Might want to make it once a majority of teams have been scouted for that match instead or make it configurable.

Current beahviour for the button is navigate from ....schedules/ to ...schedules/all/ 

![image](https://user-images.githubusercontent.com/23636955/183270544-b672c440-f5d1-42fe-89b3-b0afb554cdfc.png)
