### ISSUE TITLE
Add Edit Button

### ISSUE THREAD

**Issue by AlexanderDefuria** [AlexanderDefuria/FRC-Scouting#76]
Create link to admin panel to edit page. 

New behavior: Click match number and go to edit

@NickKerstens  Need a nice way to indicate a button to go edit. The template holds logic for permissions just need some nice styling.
@AlexanderDefuria  Make a nice template tag

**Comment by AlexanderDefuria** [comment]
Template tag is nice now.

get_edit_url model id

**Comment by NickKerstens** [comment]
Is this for the Schedule view?
