### ISSUE TITLE
Hours UI

### ISSUE THREAD

**Issue by AlexanderDefuria** [AlexanderDefuria/FRC-Scouting#81]
@NickKerstens Need to start on the View Hours. I imagine you're not happy with the current functionality / appearance. 

We should discuss how it should look.

### View Hours
![image](https://user-images.githubusercontent.com/23636955/184256793-3aa704c7-e118-475b-a002-7fc7b1c7592a.png)
### Enter (This is pretty fine)
![image](https://user-images.githubusercontent.com/23636955/184256821-5bfc9ed0-391a-4fc7-a04b-ab2bfe008a86.png)

**Comment by NickKerstens** [comment]
Let's use hours as a testing ground for the new card layout that you brought up re: MatchScout @AlexanderDefuria
