### ISSUE TITLE
Register link on index fails to load register view

### ISSUE THREAD

**Issue by NickKerstens** [AlexanderDefuria/FRC-Scouting#82]

**Comment by AlexanderDefuria** [comment]
First though is this is caused by the middleware thinking "Ope already logged in! You don't need a new account so lets put you at index." 

Need expected behavior definition.

**Comment by NickKerstens** [comment]
Since the tile only shows if you’re admin, I originally thought this was for registering your teammates. We can either get rid of this link or we can have it hard redirect to the admin panel register view. No harm in this as admins are expected to know the backend anyway

**Comment by AlexanderDefuria** [comment]
If we can redirect right to the users subpanel on admin then keep it, otherwise just drop it I think.

**Comment by AlexanderDefuria** [comment]
Dropping the subpanel from index.
