### ISSUE TITLE
Change Promotional Font

### ISSUE THREAD

**Issue by AlexanderDefuria** [AlexanderDefuria/FRC-Scouting#83]
I don't really think the promotional page style is in sync with the rest of the app.

### Current 
![image](https://user-images.githubusercontent.com/23636955/184429245-6cc715bf-3fa6-4448-b7d8-0087ba0c266a.png)
![image](https://user-images.githubusercontent.com/23636955/184429262-b590dc1c-73ae-4fa1-b884-9493f92b5828.png)
![image](https://user-images.githubusercontent.com/23636955/184429329-71ff6dc3-f753-457b-a528-3d37cee2d840.png)

**Comment by NickKerstens** [comment]
Lol.
