### ISSUE TITLE
Team uuid

### ISSUE THREAD

**Issue by mmarchjr** [AlexanderDefuria/FRC-Scouting#89]
where would I find the team uuid of my team so i can register?

**Comment by AlexanderDefuria** [comment]
The team uuid is intended to be kept private as a way for teams to validate who has access to their data and team account. Once one member of a team is registered they can share the uuid by checking the settings tab and sending it to the other people on their team. There is currently not a good solution for verifying the first member of a team other than by emailing one of the admins of the project.

 So if you could send me an email at [defuria.alexander@outlook.com](mailto:defuria.alexander@outlook.com) I will send it your team's uuid your way privately.

**Comment by AlexanderDefuria** [comment]
I've updated the main readme to reflect this information as well
